---
branches:
  - main
  - next
ci: false
tagFormat: v${version}
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: angular
      releaseRules:
        # Default release rules
        - { breaking: true, release: major }
        - { type: feat, release: minor }
        - { revert: true, release: patch }
        - { type: fix, release: patch }
        - { type: perf, release: patch }
        # Non-default release rules
        - { type: refactor, scope: "core*", release: minor }
        - { type: docs, release: patch }
        - { type: refactor, release: patch }
        - { scope: no-release, release: false }

  - - "@semantic-release/release-notes-generator"
    - preset: angular

  - - "@semantic-release/github"
    - addReleases: bottom
    # TIP: You can add "assignees" here to auto-assign issues on release failure

  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"
      changelogTitle: >
        # Changelog \n\n
        All notable changes to this project will be documented in this file. \n\n
        --- \n

  - - "@semantic-release/git"
    - assets: ["CHANGELOG.md"]
      message: "chore(release): version ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
