formatter: "markdown table"

# version: ""

# footer-from: ""

content: |-
  <!-- prettier-ignore-start -->

  ---

  ## ⚙️ Module Usage

  ### Usage Examples

  - Terragrunt: [view Terragrunt usage exmaple](examples/terragrunt.hcl)
  - Terraform: &nbsp;[view vanilla Terraform usage exmaple](examples/terraform.tf)

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  ## 📝 License

  All scripts and source code contained herein are for commercial use only by Nerdware, LLC.

  See [LICENSE](/LICENSE) for more information.

  <div align="center" style="margin-top:30px;">

  ## 💬 Contact

  Trevor Anderson - [@TeeRevTweets](https://twitter.com/teerevtweets) - [Trevor@Nerdware.cloud](mailto:trevor@nerdware.cloud)

    <a href="https://www.youtube.com/channel/UCguSCK_j1obMVXvv-DUS3ng">
      <img src="../.github/assets/YouTube_icon_circle.svg" height="40" />
    </a>
    &nbsp;
    <a href="https://www.linkedin.com/in/meet-trevor-anderson/">
      <img src="../.github/assets/LinkedIn_icon_circle.svg" height="40" />
    </a>
    &nbsp;
    <a href="https://twitter.com/TeeRevTweets">
      <img src="../.github/assets/Twitter_icon_circle.svg" height="40" />
    </a>
    &nbsp;
    <a href="mailto:trevor@nerdware.cloud">
      <img src="../.github/assets/email_icon_circle.svg" height="40" />
    </a>
    <br><br>

    <a href="https://daremightythings.co/">
      <strong><i>Dare Mighty Things.</i></strong>
    </a>

  </div>

  <!-- prettier-ignore-end -->

# recursive:
#   enabled: false
#   path: modules

# sections:
#   hide: []
#   show: []

output:
  # file: "README.md"
  mode: inject
  template: |-
    <!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
    {{ .Content }}
    <!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->

# output-values:
#   enabled: false
#   from: ""

# sort:
#   enabled: true
#   by: name

settings:
  indent: 3
  # anchor: true
  # color: true
  # default: true
  # description: false
  # escape: true
  # hide-empty: false
  # html: true
  # lockfile: true
  # read-comments: true
  # required: true
  # sensitive: true
  # type: true
